### ISSUE TITLE
Not able to import 'package:scoped_model/scoped_model.dart';

### ISSUE THREAD

**Issue by AnjuKJ** [brianegan/scoped_model#69]
My pubspec.yaml file is as follows:

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1

```
I did flutter packages get. 
Response was:
```
Running "flutter packages get" in first_app...                      0.5s
Process finished with exit code 0
```
